-- MySQL Script generated by MySQL Workbench
-- 09/30/21 15:20:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ins
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ins
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ins` ;
USE `ins` ;

-- -----------------------------------------------------
-- Table `ins`.`T_AGENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ins`.`T_AGENT` (
  `matricule` VARCHAR(10) NOT NULL,
  `photo` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `postnom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `sexe` VARCHAR(10) NULL,
  `dateNaissance` DATE NULL,
  `lieuNaissance` VARCHAR(45) NULL,
  `situationMatrimoniale` VARCHAR(25) NULL,
  `nbEnfant` INT NULL,
  `numTel` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  `ville` VARCHAR(25) NULL,
  `commune` VARCHAR(25) NULL,
  `adressePhysique` VARCHAR(45) NULL,
  `dateEmbauche` DATE NULL,
  `gradeStatut` VARCHAR(45) NULL,
  `service` VARCHAR(45) NULL,
  `mecanisation` TINYINT(1) NULL,
  `dernierDiplome` VARCHAR(45) NULL,
  `anneeObtention` DATE NULL,
  `domaineEtude` VARCHAR(45) NULL,
  `etablissement` VARCHAR(45) NULL,
  UNIQUE INDEX `matricule_UNIQUE` (`matricule` ASC),
  PRIMARY KEY (`matricule`),
  UNIQUE INDEX `photo_UNIQUE` (`photo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ins`.`T_STAGIAIRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ins`.`T_STAGIAIRE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `postnom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `sexe` VARCHAR(10) NULL,
  `dateNaissance` DATE NULL,
  `lieuNassiance` VARCHAR(45) NULL,
  `numeroTel` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  `adressePhysique` VARCHAR(45) NULL,
  `typeStagiaire` VARCHAR(15) NULL,
  `service` VARCHAR(45) NULL,
  `matricule` VARCHAR(10) NOT NULL,
  `domaineEtude` VARCHAR(45) NULL,
  `etablissement` VARCHAR(45) NULL,
  `dateDebut` DATE NULL,
  `dateFin` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `matricule_idx` (`matricule` ASC),
  CONSTRAINT `matricule`
    FOREIGN KEY (`matricule`)
    REFERENCES `ins`.`T_AGENT` (`matricule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ins`.`T_PRESENCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ins`.`T_PRESENCE` (
  `id` INT NOT NULL,
  `matricule` VARCHAR(10) NULL,
  `etatPresence` VARCHAR(10) NULL,
  `justification` VARCHAR(45) NULL,
  `dateDuJour` DATE NULL,
  `heureArriver` TIME(25) NULL,
  `heureDepart` TIME(25) NULL,
  `pieceJointe` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `matricule`
    FOREIGN KEY ()
    REFERENCES `ins`.`T_AGENT` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ins`.`T_MISSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ins`.`T_MISSION` (
  `id` INT NOT NULL,
  `matricule` VARCHAR(10) NULL,
  `codeMission` VARCHAR(45) NOT NULL,
  `objectifMission` VARCHAR(45) NULL,
  `lieuMission` VARCHAR(45) NULL,
  `dateDebut` DATE NULL,
  `dateFin` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `codeMission_UNIQUE` (`codeMission` ASC),
  CONSTRAINT `matricule`
    FOREIGN KEY ()
    REFERENCES `ins`.`T_AGENT` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ins`.`T_DOCUMENTSFOURNIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ins`.`T_DOCUMENTSFOURNIS` (
  `id` INT NOT NULL,
  `matricule` VARCHAR(10) NULL,
  `attestation1` TINYINT(1) NULL,
  `attestation2` TINYINT(1) NULL,
  `attestation3` TINYINT(1) NULL,
  `attestation4` TINYINT(1) NULL,
  `attestation5` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idT_DOCUMENTFOURNIS_UNIQUE` (`id` ASC),
  CONSTRAINT `matricule`
    FOREIGN KEY ()
    REFERENCES `ins`.`T_AGENT` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ins`.`T_CONGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ins`.`T_CONGE` (
  `id` INT NOT NULL,
  `matricule` VARCHAR(10) NULL,
  `dateDebut` DATE NULL,
  `dateFin` DATE NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idT_CONGE_UNIQUE` (`id` ASC),
  CONSTRAINT `matricule`
    FOREIGN KEY ()
    REFERENCES `ins`.`T_AGENT` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
